// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRWwo1kcbppknSht7vJfmfw0caiUMvPkY',
    appId: '1:580408848373:web:86bdc57f9c3042eaad3abc',
    messagingSenderId: '580408848373',
    projectId: 'project1-97e08',
    authDomain: 'project1-97e08.firebaseapp.com',
    storageBucket: 'project1-97e08.appspot.com',
    measurementId: 'G-9PEJD9L7X0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzDhY1ZIX1aSMshai_aVhlgztWIUhpKpA',
    appId: '1:580408848373:android:8de3ad83f737fb4aad3abc',
    messagingSenderId: '580408848373',
    projectId: 'project1-97e08',
    storageBucket: 'project1-97e08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHm1pFy572PeowE87JtETyvdtw5CoiUas',
    appId: '1:580408848373:ios:28415dffb83efe4fad3abc',
    messagingSenderId: '580408848373',
    projectId: 'project1-97e08',
    storageBucket: 'project1-97e08.appspot.com',
    iosClientId: '580408848373-126tim352uk1i0c162cjm9g0p99ns31j.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloWorld',
  );
}
